### ISSUE TITLE
Remove pysendfile dependency

### ISSUE THREAD

**Issue by maresb** [antirotor/speedcopy#19]
Apologies in case I'm mistaken, but it seems to me like the `pysendfile` dependency is only needed for legacy versions of Python. Since you require Python ≥ 3.6, I believe you can safely get rid of it.

**Comment by maresb** [comment]
Since we run `pip check` to make sure the dependencies are consistent, and `pysendfile` is no longer maintained, this is actually causing the conda-forge build https://github.com/conda-forge/speedcopy-feedstock/pull/1 to fail.

**Comment by antirotor** [comment]
Thanks for the report. Speedcopy actually still needs to support Python 2.7 so I need to fix pyproject to handle that.

**Comment by antirotor** [comment]
this should be resolved by #20
