### ISSUE TITLE
Copying doesn't work if non-absolute filenames supplied

### ISSUE THREAD

**Issue by rxxg** [antirotor/speedcopy#5]
```
speedcopy.copyfile("C:/Temp/asdf", "C:/Temp/fdsa")
```
should work exactly the same as
```
os.chdir("C:/Temp")
speedcopy.copyfile("asdf", "fdsa")
```

**Comment by rxxg** [comment]
@antirotor Would you consider releasing a 2.0.1 pypi version with this fix included?

**Comment by antirotor** [comment]
It should be done by now. I've planned to test it some more before making first 2.x "full" release. Thanks.

**Comment by rxxg** [comment]
Great, thanks.
